# Site
name: '横浜国立大学数学サークル'
description: '学生有志による数学のゼミ活動を行っています．'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'https://ynumath.netlify.app/'
disqus: ''
email: 'ynumath.integral@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-asciidoc
  - jekyll-twitter-plugin

asciidoctor:
  attributes:
  - stem

authors:
    shiba:
      name:           shiba dog
      site:           
      avatar:         /assets/images/shiba-dog-leo.jpg
      bio:            ""
      email:          shiba.dog.leo.private@gmail.com
      twitter:        https://twitter.com/shiba_dog_leo

    zab:
      name:           zab
      site:           
      avatar:         /assets/images/zab.jpg
      bio:            ""
      email:          
      twitter:        

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      


# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]